version: '3'

services:
  postgres:
    image: postgres:12-alpine 
    restart: always
    ports:
      - "54321:5432"
    volumes: 
      - /tmp/postgresql:/var/lib/postgresql
 
  app: 
    image: node:10.8
    build: src
    restart: always
    depends_on:
      - postgres
    command: npm run start-dev 
    environment:
      - DATABASE_URL:"postgres://postgres@postgres:5432/db"
      - NODE_ENV:development
      - PORT:3000
    ports:
      - "3000:3000" 
    volumes:
      - "./src:/app/"
     
